spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: 3465
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update       # Automatically create/update tables (use 'validate' or 'none' for production)
    show-sql: true          # Log generated SQL statements
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081               # Optional: set your app port here

  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true